- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      # - id: WeaponDisabler # Frontier
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenHarduit
>>>>>>> wizden/stable

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      # - id: WeaponDisabler # Frontier
      - id: NFWeaponEnergyPistolDisabler # Frontier
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      - id: ClothingBackpackElectropack
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: Binoculars
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerWarden

- type: entityTable
  id: FillLockerWarden
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: ClothingBeltSecurityFilled
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    - id: ClothingShoesBootsJack
    - id: ClothingOuterCoatWarden
    - id: ClothingOuterWinterWarden
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    - id: BookSpaceLaw
    - id: ClothingBackpackElectropack
      amount: 2
    - id: RemoteSignaller
      amount: 2
    - id: NetworkConfigurator
    - id: Binoculars

- type: entityTable
  id: FillLockerWardenHarduit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitWarden
    - id: OxygenTankFilled
    - id: ClothingMaskBreath
>>>>>>> wizden/stable

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      # - id: WeaponDisabler # Frontier
      - id: NFWeaponEnergyPistolDisabler # Frontier
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: BookSpaceLaw
        prob: 0.5
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerSecurity

- type: entityTable
  id: FillLockerSecurity
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
      prob: 0.8
    - id: WeaponDisabler
    - id: ClothingUniformJumpsuitSecGrey
      prob: 0.3
    - id: ClothingHeadHelmetBasic
    - id: ClothingOuterArmorBasic
    - id: ClothingBeltSecurityFilled
    - id: Flash
      prob: 0.5
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5
>>>>>>> wizden/stable

- type: entity
  id: LockerBrigmedicFilled
  suffix: Brigmedic, Filled
  parent: LockerBrigmedic
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
      # - id: WeaponDisabler # Frontier
      - id: NFWeaponEnergyPistolDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitBrigmedic
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
        prob: 0.1
      - id: MedkitFilled
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBrigmedic

- type: entityTable
  id: FillLockerBrigmedic
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesSecurity
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    - id: ClothingOuterHardsuitBrigmedic
    - id: BoxSterileMask
    - id: ClothingHeadHatBeretBrigmedic
    - id: ClothingOuterCoatAMG
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: ClothingUniformJumpskirtOfLife
      prob: 0.1
    - id: MedkitFilled
    - !type:GroupSelector
      prob: 0.7
      children:
>>>>>>> wizden/stable
      - id: MedkitCombatFilled
        weight: 1.6
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        weight: 0.8
      - id: MedkitBruteFilled
        weight: 0.8
      - id: MedkitToxinFilled
        weight: 0.8
      - id: MedkitBurnFilled
        weight: 1.8
    - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
      prob: 0.15

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesNoir
      - id: ClothingHeadHatDetGadget
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetectiveLoadout
      - id: FlippoEngravedLighter
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler
      - id: BoxTapeRecorder # DeltaV
        prob: 0.3
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerDetective

- type: entityTable
  id: FillLockerDetective
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesNoir
    - id: ClothingHeadHatDetGadget
    - id: ClothingNeckTieDet
    - id: ClothingOuterVestDetective
    - id: ClothingOuterCoatDetectiveLoadout
    - id: FlippoEngravedLighter
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: HandLabeler
>>>>>>> wizden/stable

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  categories: [ HideSpawnMenu ] # Frontier
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetBomb

- type: entityTable
  id: FillClosetBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    - id: Wirecutter
    - id: Screwdriver
    - id: Multitool
      prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseC1Contraband ] # Frontier: BaseSecurityContraband<BaseC1Contraband
  id: GunSafeDisabler
  name: disabler safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponEnergyPistolDisabler # Frontier: WeaponDisabler<NFWeaponEnergyPistolDisabler
      amount: 5 # Frontier
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeDisabler

- type: entityTable
  id: FillGunSafeDisabler
  table: !type:AllSelector
    children:
    - id: WeaponDisabler
      amount: 5
>>>>>>> wizden/stable

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafePistolMk58
  name: mk58 safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponPistolMk58 # Frontier: WeaponPistolMk58<NFWeaponPistolMk58
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafePistolMk58

- type: entityTable
  id: FillGunSafePistolMk58
  table: !type:AllSelector
    children:
    - id: WeaponPistolMk58
>>>>>>> wizden/stable
      amount: 4
    - id: NFMagazinePistol35 # Frontier: MagazinePistol<NFMagazinePistol35
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeRifleLecter
  name: Lecter safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponRifleAssaultLecter # Frontier: WeaponRifleLecter<NFWeaponRifleAssaultLecter
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRifleLecter

- type: entityTable
  id: FillGunSafeRifleLecter
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
>>>>>>> wizden/stable
      amount: 2
    - id: NFMagazineRifle20 # Frontier: MagazineRifle<NFMagazineRifle20
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeSubMachineGunDrozd
  name: Drozd safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponSubMachineGunDrozd # Frontier: WeaponSubMachineGunDrozd<NFWeaponSubMachineGunDrozd
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunDrozd

- type: entityTable
  id: FillGunSafeSubMachineGunDrozd
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
>>>>>>> wizden/stable
      amount: 2
    - id: NFMagazineSubMachineGun35 # Frontier: MagazinePistolSubMachineGun<NFMagazineSubMachineGun35
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeShotgunEnforcer
  name: Enforcer safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponShotgunEnforcer # Frontier: WeaponShotgunEnforcer<NFWeaponShotgunEnforcer
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunEnforcer

- type: entityTable
  id: FillGunSafeShotgunEnforcer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunEnforcer
>>>>>>> wizden/stable
      amount: 2
    - id: NFAmmunitionBoxShellShotgunBuckshot # Frontier: BoxLethalshot<NFAmmunitionBoxShellShotgunBuckshot
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  id: GunSafeShotgunKammerer
  name: Kammerer safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponShotgunKammerer # Frontier: WeaponShotgunKammerer<NFWeaponShotgunKammerer
      amount: 2
    - id: NFAmmunitionBoxShellShotgunBuckshot # Frontier: BoxLethalshot<NFAmmunitionBoxShellShotgunBuckshot
      amount: 2
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunKammerer

- type: entityTable
  id: FillGunSafeShotgunKammerer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: BoxLethalshot
      amount: 4
>>>>>>> wizden/stable

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseC2ContrabandUnredeemable ] # Frontier: BaseSecurityContraband<BaseC2ContrabandUnredeemable
  name: WT-550 safe # Frontier: caps
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponSubMachineGunWt550 # Frontier: WeaponSubMachineGunWt550<NFWeaponSubMachineGunWt550
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunWt550

- type: entityTable
  id: FillGunSafeSubMachineGunWt550
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunWt550
>>>>>>> wizden/stable
      amount: 2
    - id: NFMagazineSubMachineGunTopMounted35 # Frontier: MagazinePistolSubMachineGunTopMounted<NFMagazineSubmachineGunTopMounted35
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure] # Frontier: remove BaseSecurityContraband
  id: GunSafeLaserCarbine
  name: laser safe
  categories: [ HideSpawnMenu ] # Frontier
  components:
<<<<<<< HEAD
  - type: StorageFill
    contents:
    - id: NFWeaponEnergyRifleCarbine # Frontier: WeaponLaserCarbine<NFWeaponEnergyRifleCarbine
=======
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine

- type: entityTable
  id: FillGunSafeLaserCarbine
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
>>>>>>> wizden/stable
      amount: 3
