name: "Description: Changelogs Validator"

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-description:
    name: Validate PR Changelogs
    runs-on: ubuntu-latest
    steps:
    - name: Set up workspace
      uses: actions/checkout@v2

    - name: Validate PR Changelogs
      run: |
        # Ensure jq is installed
        sudo apt-get install jq

        # Fetch PR description using jq
        PR_DESCRIPTION=$(jq -r ".pull_request.body" "$GITHUB_EVENT_PATH")

        # Remove HTML comments from the PR description
        PR_DESCRIPTION_UNCOMMENTED=$(echo "$PR_DESCRIPTION" | sed -E ':a;N;$!ba;s/<!--([^-]|-[^-]|--[^>])*-->/\n/g')

        # Check for changelog header (:cl: or 🆑) at the start of a line, outside comments
        if ! echo "$PR_DESCRIPTION_UNCOMMENTED" | grep -Eq "^\s*(:cl:|🆑)"; then
          echo "No changelog header found at the start of a line (:cl: or 🆑) outside comments. Skipping changelog entry checks."
          exit 0
        fi

        # Extract lines after the first :cl: or 🆑 header at the start of a line
        CL_START=$(echo "$PR_DESCRIPTION_UNCOMMENTED" | grep -nE "^\s*(:cl:|🆑)" | head -n1 | cut -d: -f1)
        if [ -n "$CL_START" ]; then
          CL_BODY=$(echo "$PR_DESCRIPTION_UNCOMMENTED" | tail -n +$((CL_START + 1)))
        else
          CL_BODY=""
        fi

        # Check for at least one valid changelog entry in the format '- add:', '- remove:', '- tweak:', or '- fix:'
        if ! echo "$CL_BODY" | grep -Eq "^\s*[-*]\s*(add:|remove:|tweak:|fix:)"; then
          echo "PR description must contain at least one changelog entry in the format '- add:', '- remove:', '- tweak:', or '- fix:' (with a colon immediately after the keyword), outside comments."
          EXIT_CODE=1
        fi

        # Check that every non-empty line after :cl: is a valid changelog entry
        INVALID_ENTRIES=$(echo "$CL_BODY" | grep -Ev '^\s*$' | grep -Ev '^\s*[-*]\s*(add:|remove:|tweak:|fix:)' || true)
        if [ -n "$INVALID_ENTRIES" ]; then
          echo "Invalid changelog entry types found after :cl: (every line must start with only '- add:', '- remove:', '- tweak:', or '- fix:'):"
          echo "$INVALID_ENTRIES"
          EXIT_CODE=1
        fi

        # Exit with error if any check failed
        if [ "$EXIT_CODE" = "1" ]; then
          exit 1
        fi
