name: "Description: Changelogs Validator"

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-changelogs:
    name: Validate Changelogs
    runs-on: ubuntu-latest
    steps:
    - name: Set up workspace
      uses: actions/checkout@v2

    - name: Checkout Master
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOT_TOKEN }}
        ref: master

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Validate Changelogs
      run: |
        cd "Tools/_NF/changelog"
        node validate_changelog.js
      shell: bash
