name: "Description: Changelogs Validator"

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-description:
    name: Validate PR Changelogs
    runs-on: ubuntu-latest
    steps:
    - name: Set up workspace
      uses: actions/checkout@v2

    - name: Validate PR Changelogs
      run: node .github/Tools/_NF/validate_changelog.js
